name: Action-Test

run-name: 'Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}'

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ActionTestOutputs:
    name: Action-Test [outputs] - [${{ matrix.os }}]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        id: action-test
        with:
          Name: PSModuleTest
          WorkingDirectory: tests/outputTestRepo
          Settings: Module

  ActionTestSrcDefault:
    name: Action-Test [Src-Default] - [${{ matrix.os }}]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        id: action-test
        with:
          Name: PSModuleTest
          WorkingDirectory: tests/srcTestRepo
          Settings: SourceCode

  ActionTestsSrcWithManifest:
    name: Action-Test [Src-WithManifest] - [${{ matrix.os }}]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        id: action-test
        with:
          Name: PSModuleTest
          WorkingDirectory: tests/srcWithManifestTestRepo
          Settings: SourceCode
